name: Accion de boton para controlar lo que se hace

on: workflow_dispatch

jobs:
    test-build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: ls
              run: ls -al